matrix:
  include:
  - language: go
    go:
    - 1.11.x
    before_script:
    - echo $GOPATH
    script:
    - go build ./...
before_deploy:
- git config --local user.name "YOUR GIT USER NAME"
- git config --local user.email "YOUR GIT USER EMAIL"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: WIsjhF9NvHq3ttT2VTvs8IJ8hkzBCoMjSUEJDyHUc6rgvqrQVsuwBtbA+VYwc2DB2SGH0imTs9uuSJEPM/RTKSTHDWgrh6GRPZgpf0YuYjk9uBk22wGDL9T+XSOb641JIY7AiAnb8YSYL9w3rXpDeU19UgrOMPMewhI35KHJbGuMALJ+m//4JIJ8NkHdyFgiyYFrT4BXx4DFcV7sMiVQrsCgaUEg3gpYwdZ7sbN+N1HKkzq8UKacCTkXROtgW1wThVbBFSfn3+OG/Fsql4WbVSy9hJ+1+Pzkpv4x7em+jm6BSmOjxi2U2ClI2JMXMPjY94qsPuWcEaDZg9jv30EVJQ6e8kd8Ku8Mjgo5duhSBl//NAIwWtF/UjK7jZp9kaTnVt1j5+k2UGA1f1RIM49z+V6XBc13Xy42sgLiSP0KKOre5UE5XOGX6Vxpyt0usEhtVm6FtxQu+sAgaXSCEzRPLaoSeLGcbd8sR2Xs37daw9ifnVYhJlB3LEBeRY9/aN4Wd62Y7tyVjvhtSQZ0UkKM60MfF8BQRrfkK3zFs4z+8/JSzLpNzhLV/Z4P9L58Kv7Me/h4fiVcwCH4cFftUKoiHmKir6Vzhc73kN4ITS1uZ5AWTa7g7oCMW2DcXw4lxRHP7v1XkKOpvBpayR2TVEaxuvxE0IGLDA9oqIeWNMqXAnA=
env:
  global:
    secure: WIsjhF9NvHq3ttT2VTvs8IJ8hkzBCoMjSUEJDyHUc6rgvqrQVsuwBtbA+VYwc2DB2SGH0imTs9uuSJEPM/RTKSTHDWgrh6GRPZgpf0YuYjk9uBk22wGDL9T+XSOb641JIY7AiAnb8YSYL9w3rXpDeU19UgrOMPMewhI35KHJbGuMALJ+m//4JIJ8NkHdyFgiyYFrT4BXx4DFcV7sMiVQrsCgaUEg3gpYwdZ7sbN+N1HKkzq8UKacCTkXROtgW1wThVbBFSfn3+OG/Fsql4WbVSy9hJ+1+Pzkpv4x7em+jm6BSmOjxi2U2ClI2JMXMPjY94qsPuWcEaDZg9jv30EVJQ6e8kd8Ku8Mjgo5duhSBl//NAIwWtF/UjK7jZp9kaTnVt1j5+k2UGA1f1RIM49z+V6XBc13Xy42sgLiSP0KKOre5UE5XOGX6Vxpyt0usEhtVm6FtxQu+sAgaXSCEzRPLaoSeLGcbd8sR2Xs37daw9ifnVYhJlB3LEBeRY9/aN4Wd62Y7tyVjvhtSQZ0UkKM60MfF8BQRrfkK3zFs4z+8/JSzLpNzhLV/Z4P9L58Kv7Me/h4fiVcwCH4cFftUKoiHmKir6Vzhc73kN4ITS1uZ5AWTa7g7oCMW2DcXw4lxRHP7v1XkKOpvBpayR2TVEaxuvxE0IGLDA9oqIeWNMqXAnA=
